/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "DimensionalBlockLibrary_Master"
include(":DimensionalBlockLibrary_Main")
include(":DimensionalBlockLibrary")
include(":DimensionalBlockLibrary_v1_15_R1")
