/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.aaaaahhhhhhh.bananapuncher714.java-conventions")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

dependencies {
    implementation(project(":DimensionalBlockLibrary_Main"))
    implementation(project(":DimensionalBlockLibrary_v1_15_R1"))
}

description = "DimensionalBlockLibrary"
