/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.aaaaahhhhhhh.bananapuncher714.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT")
    implementation(project(":DimensionalBlockLibrary_Main"))
}

description = "DimensionalBlockLibrary_v1_15_R1"
